version: '3.8'

services:
  app:
    container_name: tradesilvania-project-frontend-app
    image: tradesilvania-project-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${FORWARD_APP_PORT}:${APP_PORT}
    env_file:
      - .docker.env
    environment:
      - PORT=${APP_PORT}
    depends_on:
      - redis
    networks:
      - main-network
    healthcheck:
      test: wget -nv -O /dev/null http://localhost:${APP_PORT}/api/healthcheck || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 15s

  redis:
    container_name: tradesilvania-project-frontend-redis
    image: redis:6.0.9
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${FORWARD_REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redisdata:/data
    env_file:
      - .docker.env
    networks:
      - main-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 15s
    
volumes:
  redisdata:

networks:
  main-network:
    name: tradesilvania-project-frontend-network